M48
; DRILL file {KiCad (6.0.6-0)} date 2022 July 27, Wednesday 22:33:04
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-27T22:33:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X2.8004Y-5.147
X3.028Y-5.147
T2
X2.4747Y-5.2762
T3
X2.1937Y-2.3623
X2.9169Y-4.445
X2.9185Y-1.7552
X3.6232Y-2.3623
T0
M30
