M48
; DRILL file {KiCad (6.0.0-0)} date 2022 March 22, Tuesday 14:17:05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-22T14:17:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X2.4894Y-3.5887
T2
X2.1972Y-5.1613
X2.6692Y-5.1613
T0
M30
